"""Service templates for citizen forms that are still paper, block-letter, affidavit,
or CSC/counter-assisted in India.

fill_mode (evidence-backed):
  paper_block_letters — official form still says BLOCK/CAPITAL letters or paper PDF
  paper_or_online     — statute/portal allows offline paper + online
  assisted_counter    — CSC/branch/tehsil operator types from citizen docs / annexures
  portal_identity     — mostly online; desk still needed for name/DOB mismatch remediation

Validation rules live in knowledge_base.py.
"""

from __future__ import annotations

SERVICES = {
    # Primary source: UIDAI Form 1 PDF — "use only upper case (block or capital) letters."
    # https://uidai.gov.in/images/Form_1_Eng.pdf
    "link_mobile_aadhaar": {
        "id": "link_mobile_aadhaar",
        "title": "Aadhaar Form 1 — Enrolment / Demographic Update",
        "category": "Aadhaar",
        "fill_mode": "paper_block_letters",
        "official_form": "UIDAI Form 1: Aadhaar Enrolment and Update",
        "source_url": "https://uidai.gov.in/images/Form_1_Eng.pdf",
        "tagline": "Official ASK paper form — BLOCK LETTERS; fill only fields being updated.",
        "why": (
            "UIDAI Form 1 is still the counter form at Aadhaar Seva Kendras. Instructions: "
            "use only upper-case (block/capital) letters; for updates fill only fields to change "
            "(name, gender, DOB, address, mobile, email). Name must match POI without titles. "
            "Operator/citizen transcription errors here break OTP and every downstream KYC."
        ),
        "required_docs": ["Aadhaar Card"],
        "optional_docs": ["PAN Card", "Bank Passbook", "Voter ID", "Ration Card"],
        "portal": {
            "name": "Aadhaar Seva Kendra / myAadhaar",
            "url": "https://myaadhaar.uidai.gov.in",
        },
        "demo_answers": "sample_form_answers.json",
        "form_fields": [
            {"key": "update_fields", "label": "Fields to Update (name/DOB/address/mobile/email/gender)",
             "prompt_hi": "आधार में क्या अपडेट करना है — नाम, जन्म तिथि, पता, मोबाइल, ईमेल, लिंग?",
             "prompt_en": "What to update on Aadhaar — name, DOB, address, mobile, email, gender?",
             "high_stakes": True, "compare_to": None},
            {"key": "full_name", "label": "Full Name (as on POI, no titles)",
             "prompt_hi": "पूरा नाम बताइए जैसा पहचान पत्र पर है — श्री/श्रीमती न लगाएँ।",
             "prompt_en": "Full name as on proof of identity, omitting titles.",
             "high_stakes": True, "compare_to": "full_name", "compare_doc": "Aadhaar Card"},
            {"key": "dob", "label": "Date of Birth",
             "prompt_hi": "जन्म तिथि बताइए — दिन, महीना, साल।",
             "prompt_en": "Date of birth — day, month, year.",
             "high_stakes": True, "compare_to": "dob", "compare_doc": "Aadhaar Card"},
            {"key": "aadhaar_number", "label": "Aadhaar Number (for update)",
             "prompt_hi": "बारह अंकों का आधार नंबर बताइए।",
             "prompt_en": "Twelve-digit Aadhaar number.",
             "high_stakes": True, "compare_to": "id_number", "compare_doc": "Aadhaar Card"},
            {"key": "mobile", "label": "Mobile Number",
             "prompt_hi": "मोबाइल नंबर बताइए।",
             "prompt_en": "Mobile number.",
             "high_stakes": True, "compare_to": None},
            {"key": "email", "label": "Email (if updating)",
             "prompt_hi": "ईमेल अगर अपडेट करना है तो बताइए।",
             "prompt_en": "Email if updating.",
             "high_stakes": False, "compare_to": None},
            {"key": "gender", "label": "Gender",
             "prompt_hi": "लिंग बताइए — पुरुष, महिला या अन्य।",
             "prompt_en": "Gender — male, female, or third gender.",
             "high_stakes": False, "compare_to": None},
            {"key": "address", "label": "Address (PIN + post office mandatory on Form 1)",
             "prompt_hi": "पूरा पता बताइए — पिनकोड और पोस्ट ऑफिस ज़रूर।",
             "prompt_en": "Full address — pincode and post office are mandatory on Form 1.",
             "high_stakes": True, "compare_to": "address", "compare_doc": "Aadhaar Card"},
        ],
    },
    # Primary: parivahan.gov.in — apply ONLINE on Sarathi; Form-2 PDF still published; RTO visit for originals.
    "rto_dl_update": {
        "id": "rto_dl_update",
        "title": "RTO — Driving Licence Address / Name Update",
        "category": "Transport",
        "fill_mode": "assisted_counter",
        "official_form": "CMVR Form 2 / Sarathi Services on DL",
        "source_url": "https://parivahan.gov.in/en/node/246",
        "tagline": "Sarathi online apply + RTO counter with originals — Form 2 still published.",
        "why": (
            "MoRTH/Parivahan says change of address is applied ONLINE on Sarathi, then citizen "
            "visits RTO with originals. CMVR Form 2 (learner/DL/renewal/change of address or name) "
            "is still published as a downloadable form. CSC desks commonly type from DL + Aadhaar; "
            "wrong DL number or address without pincode still rejects."
        ),
        "required_docs": ["Driving License", "Aadhaar Card"],
        "optional_docs": ["PAN Card", "Bank Passbook", "Ration Card"],
        "portal": {
            "name": "Parivahan Sarathi — Change of Address / Name in DL",
            "url": "https://sarathi.parivahan.gov.in",
        },
        "demo_answers": "sample_form_sanika.json",
        "form_fields": [
            {"key": "full_name", "label": "Full Name",
             "prompt_hi": "अपना पूरा नाम बताइए।",
             "prompt_en": "Please say your full name.",
             "high_stakes": True, "compare_to": "full_name"},
            {"key": "father_name", "label": "Father's / Guardian's Name",
             "prompt_hi": "अपने पिता या अभिभावक का नाम बताइए।",
             "prompt_en": "Please say your father's or guardian's name.",
             "high_stakes": True, "compare_to": "father_name", "compare_doc": "Aadhaar Card"},
            {"key": "dl_number", "label": "Driving Licence Number",
             "prompt_hi": "अपना ड्राइविंग लाइसेंस नंबर बताइए।",
             "prompt_en": "Please say your driving licence number.",
             "high_stakes": False, "compare_to": "id_number", "compare_doc": "Driving License"},
            {"key": "pan_number", "label": "PAN Number",
             "prompt_hi": "दस अक्षर का पैन नंबर बताइए।",
             "prompt_en": "Ten-character PAN number.",
             "high_stakes": False, "compare_to": "id_number", "compare_doc": "PAN Card"},
            {"key": "dob", "label": "Date of Birth",
             "prompt_hi": "अपनी जन्म तिथि बताइए।",
             "prompt_en": "Please say your date of birth.",
             "high_stakes": True, "compare_to": "dob"},
            {"key": "mobile", "label": "Mobile Number",
             "prompt_hi": "अपना मोबाइल नंबर बताइए।",
             "prompt_en": "Please say your mobile number.",
             "high_stakes": False, "compare_to": None},
            {"key": "change_type", "label": "What to Change",
             "prompt_hi": "आप क्या बदलना चाहते हैं — नाम, पता, या दोनों?",
             "prompt_en": "What do you want to change — name, address, or both?",
             "high_stakes": False, "compare_to": None},
            {"key": "old_address", "label": "Address on Current DL",
             "prompt_hi": "लाइसेंस पर अभी कौन सा पता लिखा है?",
             "prompt_en": "What address is currently printed on your licence?",
             "high_stakes": False, "compare_to": "address", "compare_doc": "Driving License"},
            {"key": "new_address", "label": "New Address (with pincode)",
             "prompt_hi": "नया पता बताइए — पिनकोड ज़रूर बताएं।",
             "prompt_en": "Please say your new address, including pincode.",
             "high_stakes": True, "compare_to": "address", "compare_doc": "Aadhaar Card"},
        ],
    },
    "scheme_apply": {
        "id": "scheme_apply",
        "title": "Gov Scheme Discovery + Darkhast (Application)",
        "category": "Schemes",
        "fill_mode": "assisted_counter",
        "official_form": "Scheme-specific CSC / myScheme application (varies by scheme)",
        "source_url": "https://www.myscheme.gov.in",
        "tagline": "CSC-assisted portal fill — identity + income/category mismatch kills DBT.",
        "why": (
            "Not one national paper form — CSC operators still fill PM-KISAN / Ayushman / e-Shram "
            "portals from Aadhaar + ration + passbook. Applications bounce on income/category/"
            "Aadhaar-mobile mismatch more than on missing checkboxes."
        ),
        "required_docs": ["Aadhaar Card", "Ration Card"],
        "optional_docs": ["Bank Passbook", "School Certificate"],
        "portal": {
            "name": "National / State scheme portals (via CSC)",
            "url": "https://www.myscheme.gov.in",
        },
        "demo_answers": "sample_form_scheme.json",
        "form_fields": [
            {"key": "full_name", "label": "Applicant Full Name",
             "prompt_hi": "आवेदक का पूरा नाम बताइए।",
             "prompt_en": "Please say the applicant's full name.",
             "high_stakes": True, "compare_to": "full_name"},
            {"key": "aadhaar_number", "label": "Aadhaar Number",
             "prompt_hi": "आधार नंबर बताइए।",
             "prompt_en": "Please say the Aadhaar number.",
             "high_stakes": True, "compare_to": "id_number", "compare_doc": "Aadhaar Card"},
            {"key": "dob", "label": "Date of Birth",
             "prompt_hi": "जन्म तिथि बताइए।",
             "prompt_en": "Please say date of birth.",
             "high_stakes": True, "compare_to": "dob"},
            {"key": "mobile", "label": "Mobile (Aadhaar-linked)",
             "prompt_hi": "आधार से जुड़ा मोबाइल नंबर बताइए।",
             "prompt_en": "Please say the Aadhaar-linked mobile number.",
             "high_stakes": True, "compare_to": None},
            {"key": "address", "label": "Address with pincode",
             "prompt_hi": "पूरा पता पिनकोड के साथ बताइए।",
             "prompt_en": "Please say full address with pincode.",
             "high_stakes": True, "compare_to": "address"},
            {"key": "scheme_name", "label": "Scheme Name",
             "prompt_hi": "कौन सी योजना के लिए आवेदन करना है? जैसे पीएम किसान, आयुष्मान, ई-श्रम।",
             "prompt_en": "Which scheme? e.g. PM-KISAN, Ayushman, e-Shram.",
             "high_stakes": True, "compare_to": None},
            {"key": "category", "label": "Category (SC/ST/OBC/EWS/General)",
             "prompt_hi": "आपकी श्रेणी क्या है — अनुसूचित जाति, जनजाति, ओबीसी, ईडब्ल्यूएस या सामान्य?",
             "prompt_en": "What is your category — SC, ST, OBC, EWS, or General?",
             "high_stakes": True, "compare_to": None},
            {"key": "annual_income", "label": "Approx Annual Family Income (₹)",
             "prompt_hi": "परिवार की सालाना आय लगभग कितनी है?",
             "prompt_en": "What is approximate annual family income in rupees?",
             "high_stakes": True, "compare_to": None},
        ],
    },
    "grievance_complaint": {
        "id": "grievance_complaint",
        "title": "File a Government Service Complaint",
        "category": "Grievance",
        "fill_mode": "portal_identity",
        "official_form": "CPGRAMS / state public grievance",
        "source_url": "https://pgportal.gov.in",
        "tagline": "Online grievance — desk value is factual capture, not paper ICR.",
        "why": (
            "CPGRAMS is online. Include only because rejected Aadhaar/RTO/scheme cases need a "
            "clean factual complaint with identity refs; vague filings get closed."
        ),
        "required_docs": ["Aadhaar Card"],
        "optional_docs": ["Rejection letter", "Acknowledgement receipt"],
        "portal": {
            "name": "CPGRAMS / State public grievance portal",
            "url": "https://pgportal.gov.in",
        },
        "demo_answers": "sample_form_complaint.json",
        "form_fields": [
            {"key": "full_name", "label": "Full Name",
             "prompt_hi": "अपना नाम बताइए।",
             "prompt_en": "Please say your name.",
             "high_stakes": True, "compare_to": "full_name"},
            {"key": "mobile", "label": "Mobile",
             "prompt_hi": "मोबाइल नंबर बताइए।",
             "prompt_en": "Please say your mobile number.",
             "high_stakes": True, "compare_to": None},
            {"key": "aadhaar_number", "label": "Aadhaar Number",
             "prompt_hi": "आधार नंबर बताइए।",
             "prompt_en": "Please say your Aadhaar number.",
             "high_stakes": True, "compare_to": "id_number", "compare_doc": "Aadhaar Card"},
            {"key": "department", "label": "Department / Office",
             "prompt_hi": "किस विभाग या दफ्तर से शिकायत है — आधार, आरटीओ, योजना?",
             "prompt_en": "Which department — Aadhaar, RTO, scheme office?",
             "high_stakes": True, "compare_to": None},
            {"key": "complaint_summary", "label": "What Happened (facts)",
             "prompt_hi": "क्या समस्या हुई — तारीख और संदर्भ नंबर के साथ बताइए।",
             "prompt_en": "What went wrong — include dates and any reference number.",
             "high_stakes": True, "compare_to": None},
            {"key": "desired_outcome", "label": "What You Want Done",
             "prompt_hi": "आप क्या चाहते हैं — सुधार, स्टेटस, या दोबारा आवेदन?",
             "prompt_en": "What outcome do you want — correction, status, or re-apply?",
             "high_stakes": True, "compare_to": None},
        ],
    },
    "pan_aadhaar_link": {
        "id": "pan_aadhaar_link",
        "title": "Link PAN with Aadhaar",
        "category": "Tax / PAN",
        "fill_mode": "portal_identity",
        "official_form": "Income-tax e-Filing — Link Aadhaar (online)",
        "source_url": "https://eportal.incometax.gov.in",
        "tagline": "Online link — desk value is name/DOB match; fix via PAN CR if it fails.",
        "why": (
            "Linking itself is online on the e-Filing portal — not a block-letter paper form. "
            "Keep on the desk because Mohd/Mohammed-style mismatches fail the link; remediation "
            "is usually PAN Change Request (paper/online), not retrying the link."
        ),
        "required_docs": ["Aadhaar Card", "PAN Card"],
        "optional_docs": ["Bank Passbook"],
        "portal": {
            "name": "Income Tax e-Filing — Link Aadhaar",
            "url": "https://eportal.incometax.gov.in",
        },
        "demo_answers": "sample_form_pan.json",
        "form_fields": [
            {"key": "full_name", "label": "Full Name (as on PAN)",
             "prompt_hi": "पैन पर लिखा पूरा नाम बताइए।",
             "prompt_en": "Full name as on PAN.",
             "high_stakes": True, "compare_to": "full_name", "compare_doc": "PAN Card"},
            {"key": "pan_number", "label": "PAN Number",
             "prompt_hi": "दस अक्षर का पैन नंबर बताइए।",
             "prompt_en": "Ten-character PAN number.",
             "high_stakes": True, "compare_to": "id_number", "compare_doc": "PAN Card"},
            {"key": "aadhaar_number", "label": "Aadhaar Number",
             "prompt_hi": "आधार नंबर बताइए।",
             "prompt_en": "Aadhaar number.",
             "high_stakes": True, "compare_to": "id_number", "compare_doc": "Aadhaar Card"},
            {"key": "dob", "label": "Date of Birth",
             "prompt_hi": "जन्म तिथि बताइए।",
             "prompt_en": "Date of birth.",
             "high_stakes": True, "compare_to": "dob", "compare_doc": "PAN Card"},
            {"key": "mobile", "label": "Registered Mobile",
             "prompt_hi": "रजिस्टर्ड मोबाइल बताइए।",
             "prompt_en": "Registered mobile.",
             "high_stakes": True, "compare_to": None},
        ],
    },
    # Primary: ECI — offline Form 8 still valid at ERO/AERO/BLO; PDF on voters.eci.gov.in
    # https://www.eci.gov.in/faq/en/how-to-register/
    "voter_form8": {
        "id": "voter_form8",
        "title": "Voter ID — Form 8 (Correction / Shift / EPIC)",
        "category": "Elections",
        "fill_mode": "paper_or_online",
        "official_form": "ECI Form 8 (Registration of Electors Rules, 1960)",
        "source_url": "https://voters.eci.gov.in/formspdf/Form_8_English.pdf",
        "tagline": "Statutory Form 8 — online OR free paper at BLO/ERO; photo paste on print.",
        "why": (
            "ECI still offers offline Form 8 free at ERO/AERO/BLO offices (also online on VSP). "
            "Paper path: print PDF, paste passport photo, self-attest proofs, hand to BLO or post "
            "to ERO. Name/DOB/address vs Aadhaar/EPIC mismatches are classic rejections."
        ),
        "required_docs": ["Aadhaar Card", "Voter ID"],
        "optional_docs": ["Ration Card", "Bank Passbook", "Electricity Bill"],
        "portal": {
            "name": "Voters' Services Portal — Form 8",
            "url": "https://voters.eci.gov.in",
        },
        "form_fields": [
            {"key": "full_name", "label": "Full Name (as in electoral roll)",
             "prompt_hi": "मतदाता सूची में लिखा पूरा नाम बताइए।",
             "prompt_en": "Full name as in the electoral roll.",
             "high_stakes": True, "compare_to": "full_name", "compare_doc": "Voter ID"},
            {"key": "epic_number", "label": "EPIC / Voter ID Number",
             "prompt_hi": "अपना वोटर आईडी या ईपीआईसी नंबर बताइए।",
             "prompt_en": "Please say your EPIC / voter ID number.",
             "high_stakes": True, "compare_to": "id_number", "compare_doc": "Voter ID"},
            {"key": "dob", "label": "Date of Birth / Age",
             "prompt_hi": "जन्म तिथि या आयु बताइए।",
             "prompt_en": "Date of birth or age on the roll.",
             "high_stakes": True, "compare_to": "dob", "compare_doc": "Aadhaar Card"},
            {"key": "aadhaar_number", "label": "Aadhaar Number",
             "prompt_hi": "आधार नंबर बताइए।",
             "prompt_en": "Aadhaar number.",
             "high_stakes": True, "compare_to": "id_number", "compare_doc": "Aadhaar Card"},
            {"key": "mobile", "label": "Mobile Number",
             "prompt_hi": "मोबाइल नंबर बताइए।",
             "prompt_en": "Mobile number.",
             "high_stakes": True, "compare_to": None},
            {"key": "request_type", "label": "Request Type",
             "prompt_hi": "क्या करना है — नाम/पता सुधार, निवास स्थान बदलाव, या नया ईपीआईसी?",
             "prompt_en": "Correction, shift of residence, or EPIC replacement?",
             "high_stakes": True, "compare_to": None},
            {"key": "correction_fields", "label": "What to Correct (max 4)",
             "prompt_hi": "कौन सी प्रविष्टियाँ गलत हैं — नाम, जन्म तिथि, पता, फोटो?",
             "prompt_en": "Which entries to fix — name, DOB, address, photo?",
             "high_stakes": True, "compare_to": None},
            {"key": "new_address", "label": "Correct / New Address (with PIN)",
             "prompt_hi": "सही या नया पता पिनकोड के साथ बताइए।",
             "prompt_en": "Correct or new address including pincode.",
             "high_stakes": True, "compare_to": "address", "compare_doc": "Aadhaar Card"},
            {"key": "father_name", "label": "Relation Name (Father/Mother/Spouse)",
             "prompt_hi": "पिता, माता या पति/पत्नी का नाम बताइए।",
             "prompt_en": "Father's, mother's, or spouse's name.",
             "high_stakes": False, "compare_to": "father_name", "compare_doc": "Aadhaar Card"},
        ],
    },
    "voter_form6": {
        "id": "voter_form6",
        "title": "Voter ID — Form 6 (New Enrolment)",
        "category": "Elections",
        "fill_mode": "paper_or_online",
        "official_form": "ECI Form 6 — Application Form for New Voters",
        "source_url": "https://voters.eci.gov.in/formspdf/Form_6_English.pdf",
        "tagline": "Form 6 — English name in BLOCK LETTERS; offline at BLO still valid.",
        "why": (
            "ECI Form 6 PDF requires name in English in BLOCK LETTERS and a pasted photograph. "
            "Official FAQ: enrol offline — form free at ERO/AERO/BLO; file in person, by post, "
            "or hand to BLO. Aadhaar demographic mismatch is a top rejection reason."
        ),
        "required_docs": ["Aadhaar Card"],
        "optional_docs": ["Ration Card", "School Certificate", "Birth Certificate"],
        "portal": {
            "name": "Voters' Services Portal — Form 6",
            "url": "https://voters.eci.gov.in",
        },
        "form_fields": [
            {"key": "full_name", "label": "Applicant Full Name",
             "prompt_hi": "आवेदक का पूरा नाम बताइए।",
             "prompt_en": "Applicant's full name.",
             "high_stakes": True, "compare_to": "full_name", "compare_doc": "Aadhaar Card"},
            {"key": "father_name", "label": "Father's / Mother's / Husband's Name",
             "prompt_hi": "पिता, माता या पति का नाम बताइए।",
             "prompt_en": "Father's, mother's, or husband's name.",
             "high_stakes": True, "compare_to": "father_name", "compare_doc": "Aadhaar Card"},
            {"key": "dob", "label": "Date of Birth",
             "prompt_hi": "जन्म तिथि बताइए।",
             "prompt_en": "Date of birth.",
             "high_stakes": True, "compare_to": "dob", "compare_doc": "Aadhaar Card"},
            {"key": "aadhaar_number", "label": "Aadhaar Number",
             "prompt_hi": "आधार नंबर बताइए।",
             "prompt_en": "Aadhaar number.",
             "high_stakes": True, "compare_to": "id_number", "compare_doc": "Aadhaar Card"},
            {"key": "mobile", "label": "Mobile Number",
             "prompt_hi": "मोबाइल नंबर बताइए।",
             "prompt_en": "Mobile number.",
             "high_stakes": True, "compare_to": None},
            {"key": "gender", "label": "Gender",
             "prompt_hi": "लिंग बताइए — पुरुष, महिला या अन्य।",
             "prompt_en": "Gender — male, female, or other.",
             "high_stakes": True, "compare_to": None},
            {"key": "address", "label": "Ordinary Residence Address (with PIN)",
             "prompt_hi": "साधारण निवास का पूरा पता पिनकोड के साथ बताइए।",
             "prompt_en": "Ordinary residence address with pincode.",
             "high_stakes": True, "compare_to": "address", "compare_doc": "Aadhaar Card"},
            {"key": "assembly_constituency", "label": "Assembly Constituency (if known)",
             "prompt_hi": "विधानसभा क्षेत्र का नाम अगर पता हो तो बताइए।",
             "prompt_en": "Assembly constituency name if known.",
             "high_stakes": False, "compare_to": None},
        ],
    },
    "passport_apply": {
        "id": "passport_apply",
        "title": "Passport Application (CSC / PSK Assisted)",
        "category": "Passport",
        "fill_mode": "paper_block_letters",
        "official_form": "Passport Application + Supplementary Form (ICR) / Annexures",
        "source_url": "https://www.passportindia.gov.in/AppOnlineProject/pdf/ApplicationformInstructionBooklet-V3.0.pdf",
        "tagline": "Official instructions: CAPITAL LETTERS, ball-point, ICR scan; annexures on plain/stamp paper.",
        "why": (
            "Passport Seva instruction booklet: form is machine-readable for ICR scanners; "
            "use CAPITAL LETTERS only; black/blue ball-point; leave blank box between words. "
            "CSC/DPC path still pastes photograph. Annexures C/D/K etc. are specimen declarations "
            "on plain paper or non-judicial stamp paper — filled by hand. Given name/surname/DOB "
            "must match Aadhaar or old passport."
        ),
        "required_docs": ["Aadhaar Card"],
        "optional_docs": ["PAN Card", "Voter ID", "Bank Passbook", "Old Passport"],
        "portal": {
            "name": "Passport Seva — Fresh / Re-issue",
            "url": "https://www.passportindia.gov.in",
        },
        "form_fields": [
            {"key": "full_name", "label": "Given Name + Surname (as on Aadhaar)",
             "prompt_hi": "आधार जैसा पूरा नाम — नाम और सरनेम अलग-अलग बताइए।",
             "prompt_en": "Given name and surname exactly as on Aadhaar.",
             "high_stakes": True, "compare_to": "full_name", "compare_doc": "Aadhaar Card"},
            {"key": "father_name", "label": "Father's / Legal Guardian's Name",
             "prompt_hi": "पिता या अभिभावक का नाम बताइए।",
             "prompt_en": "Father's or legal guardian's name.",
             "high_stakes": True, "compare_to": "father_name", "compare_doc": "Aadhaar Card"},
            {"key": "dob", "label": "Date of Birth",
             "prompt_hi": "जन्म तिथि बताइए।",
             "prompt_en": "Date of birth.",
             "high_stakes": True, "compare_to": "dob", "compare_doc": "Aadhaar Card"},
            {"key": "place_of_birth", "label": "Place of Birth (village/town + district + state)",
             "prompt_hi": "जन्म स्थान — गाँव/शहर, ज़िला, राज्य बताइए।",
             "prompt_en": "Place of birth — town, district, state.",
             "high_stakes": True, "compare_to": None},
            {"key": "aadhaar_number", "label": "Aadhaar Number",
             "prompt_hi": "आधार नंबर बताइए।",
             "prompt_en": "Aadhaar number.",
             "high_stakes": True, "compare_to": "id_number", "compare_doc": "Aadhaar Card"},
            {"key": "mobile", "label": "Mobile Number",
             "prompt_hi": "मोबाइल नंबर बताइए।",
             "prompt_en": "Mobile number.",
             "high_stakes": True, "compare_to": None},
            {"key": "email", "label": "Email Address",
             "prompt_hi": "ईमेल पता बताइए।",
             "prompt_en": "Email address.",
             "high_stakes": True, "compare_to": None},
            {"key": "address", "label": "Present Address (with PIN)",
             "prompt_hi": "वर्तमान पता पिनकोड के साथ बताइए।",
             "prompt_en": "Present address with pincode.",
             "high_stakes": True, "compare_to": "address", "compare_doc": "Aadhaar Card"},
            {"key": "service_type", "label": "Fresh Passport or Re-issue",
             "prompt_hi": "नया पासपोर्ट चाहिए या पुराना बदलना है?",
             "prompt_en": "Fresh passport or re-issue?",
             "high_stakes": True, "compare_to": None},
            {"key": "old_passport_number", "label": "Old Passport Number (if re-issue)",
             "prompt_hi": "अगर पुराना पासपोर्ट है तो नंबर बताइए।",
             "prompt_en": "Old passport number if re-issuing.",
             "high_stakes": False, "compare_to": "id_number", "compare_doc": "Old Passport"},
        ],
    },
    "pan_correction": {
        "id": "pan_correction",
        "title": "PAN Correction / Change Request",
        "category": "Tax / PAN",
        "fill_mode": "paper_block_letters",
        "official_form": "Request for New PAN Card Or/And Changes or Correction in PAN Data (PAN CR)",
        "source_url": "https://incometaxindia.gov.in/Documents/form-for-changes-in-pan.pdf",
        "tagline": "ITD/Protean/UTIITSL — BLOCK LETTERS physical OR online; print+post proofs common.",
        "why": (
            "DGIT (Systems): PAN CR forms can be submitted physically at UTIITSL/Protean "
            "centres or online. Instructions: BLOCK LETTERS, preferably black ink, English only; "
            "tick left-margin boxes for fields being corrected. Protean online path still often "
            "needs signed acknowledgment + physical proofs. Real fix when Aadhaar↔PAN link fails."
        ),
        "required_docs": ["PAN Card", "Aadhaar Card"],
        "optional_docs": ["Birth Certificate", "Gazette Notification", "Marriage Certificate"],
        "portal": {
            "name": "Protean / UTIITSL — PAN Change Request",
            "url": "https://www.onlineservices.nsdl.com/paam/endUserRegisterContact.html",
        },
        "form_fields": [
            {"key": "full_name", "label": "Correct Full Name (no titles)",
             "prompt_hi": "सही पूरा नाम बताइए — श्री/श्रीमती न लगाएँ।",
             "prompt_en": "Correct full name without titles like Shri/Smt.",
             "high_stakes": True, "compare_to": "full_name", "compare_doc": "Aadhaar Card"},
            {"key": "pan_number", "label": "Existing PAN Number",
             "prompt_hi": "मौजूदा पैन नंबर बताइए।",
             "prompt_en": "Existing PAN number.",
             "high_stakes": True, "compare_to": "id_number", "compare_doc": "PAN Card"},
            {"key": "father_name", "label": "Father's Name (as to be printed)",
             "prompt_hi": "पिता का नाम बताइए जैसा पैन पर चाहिए।",
             "prompt_en": "Father's name as it should appear on PAN.",
             "high_stakes": True, "compare_to": "father_name", "compare_doc": "Aadhaar Card"},
            {"key": "dob", "label": "Correct Date of Birth",
             "prompt_hi": "सही जन्म तिथि बताइए।",
             "prompt_en": "Correct date of birth.",
             "high_stakes": True, "compare_to": "dob", "compare_doc": "Aadhaar Card"},
            {"key": "aadhaar_number", "label": "Aadhaar Number",
             "prompt_hi": "आधार नंबर बताइए।",
             "prompt_en": "Aadhaar number.",
             "high_stakes": True, "compare_to": "id_number", "compare_doc": "Aadhaar Card"},
            {"key": "mobile", "label": "Mobile Number",
             "prompt_hi": "मोबाइल नंबर बताइए।",
             "prompt_en": "Mobile number.",
             "high_stakes": True, "compare_to": None},
            {"key": "fields_to_correct", "label": "Fields Being Corrected",
             "prompt_hi": "क्या सुधारना है — नाम, पिता का नाम, जन्म तिथि, पता?",
             "prompt_en": "What are you correcting — name, father's name, DOB, address?",
             "high_stakes": True, "compare_to": None},
            {"key": "address", "label": "Address on PAN (with PIN)",
             "prompt_hi": "पैन पर दर्ज पता पिनकोड के साथ बताइए।",
             "prompt_en": "Address for PAN with pincode.",
             "high_stakes": False, "compare_to": "address", "compare_doc": "Aadhaar Card"},
        ],
    },
    "ration_card_update": {
        "id": "ration_card_update",
        "title": "Ration Card — New / Member Add / Correction",
        "category": "Food / Ration",
        "fill_mode": "assisted_counter",
        "official_form": "State Food & Civil Supplies / NFSA e-KYC application (state portal)",
        "source_url": "https://nfsa.gov.in",
        "tagline": "State portals via CSC — operator-filled; Aadhaar e-KYC name match is the blocker.",
        "why": (
            "No single national paper ICR form — NFSA/state food portals are filled at CSC/FPS "
            "from Aadhaar + ration booklet. Head-of-family name/DOB mismatches fail e-KYC. "
            "Include as assisted-counter identity work, not as a block-letter national form."
        ),
        "required_docs": ["Aadhaar Card"],
        "optional_docs": ["Ration Card", "Bank Passbook", "Electricity Bill", "Voter ID"],
        "portal": {
            "name": "State Food & Civil Supplies / NFSA (via CSC)",
            "url": "https://nfsa.gov.in",
        },
        "form_fields": [
            {"key": "full_name", "label": "Applicant / Head of Family Name",
             "prompt_hi": "आवेदक या परिवार मुखिया का नाम बताइए।",
             "prompt_en": "Applicant or head-of-family name.",
             "high_stakes": True, "compare_to": "full_name", "compare_doc": "Aadhaar Card"},
            {"key": "ration_card_number", "label": "Existing Ration Card Number (or NEW)",
             "prompt_hi": "राशन कार्ड नंबर बताइए, या नया कार्ड हो तो NEW कहिए।",
             "prompt_en": "Existing ration card number, or say NEW.",
             "high_stakes": True, "compare_to": "id_number", "compare_doc": "Ration Card"},
            {"key": "aadhaar_number", "label": "Aadhaar Number",
             "prompt_hi": "आधार नंबर बताइए।",
             "prompt_en": "Aadhaar number.",
             "high_stakes": True, "compare_to": "id_number", "compare_doc": "Aadhaar Card"},
            {"key": "dob", "label": "Date of Birth",
             "prompt_hi": "जन्म तिथि बताइए।",
             "prompt_en": "Date of birth.",
             "high_stakes": True, "compare_to": "dob", "compare_doc": "Aadhaar Card"},
            {"key": "mobile", "label": "Mobile (OTP)",
             "prompt_hi": "ओटीपी वाला मोबाइल नंबर बताइए।",
             "prompt_en": "Mobile number for OTP.",
             "high_stakes": True, "compare_to": None},
            {"key": "request_type", "label": "Request Type",
             "prompt_hi": "नया कार्ड, सदस्य जोड़ना, नाम सुधार, या पता बदलाव?",
             "prompt_en": "New card, add member, name fix, or address change?",
             "high_stakes": True, "compare_to": None},
            {"key": "card_type", "label": "Card Type (AAY / PHH / State)",
             "prompt_hi": "कार्ड प्रकार — अंत्योदय, प्राथमिक, या राज्य का प्रकार?",
             "prompt_en": "Card type — AAY, PHH, or state category?",
             "high_stakes": True, "compare_to": None},
            {"key": "address", "label": "Address with pincode",
             "prompt_hi": "पूरा पता पिनकोड के साथ बताइए।",
             "prompt_en": "Full address with pincode.",
             "high_stakes": True, "compare_to": "address", "compare_doc": "Aadhaar Card"},
            {"key": "family_members", "label": "Family Members Being Added/Corrected",
             "prompt_hi": "जिन सदस्यों को जोड़ना या सुधारना है उनके नाम बताइए।",
             "prompt_en": "Names of members being added or corrected.",
             "high_stakes": False, "compare_to": None},
        ],
    },
    "caste_income_certificate": {
        "id": "caste_income_certificate",
        "title": "Caste / Income / Domicile Certificate",
        "category": "Tehsil / Setu",
        "fill_mode": "paper_or_online",
        "official_form": "State application + caste affidavit (e.g. MH Form 2 / Form 3)",
        "source_url": "https://rd.mahaonline.gov.in/PDF/CasteAffidavit_FORM-2.pdf",
        "tagline": "e-District online + mandatory handwritten affidavits (MH Form 2/3 verified).",
        "why": (
            "Maharashtra Aaple Sarkar lists Affidavit Form-2 and Form-3 as mandatory for caste "
            "certificate — blank-line affidavits signed on paper with genealogy. Online filing "
            "exists; the affidavit layer is still longhand. Name spelling across Aadhaar/ration/"
            "school TC decides approval."
        ),
        "required_docs": ["Aadhaar Card", "Ration Card"],
        "optional_docs": ["School Certificate", "Property Tax Receipt", "Bank Passbook"],
        "portal": {
            "name": "State e-District / Setu / CSC certificate services",
            "url": "https://www.india.gov.in",
        },
        "form_fields": [
            {"key": "full_name", "label": "Applicant Full Name",
             "prompt_hi": "आवेदक का पूरा नाम बताइए।",
             "prompt_en": "Applicant's full name.",
             "high_stakes": True, "compare_to": "full_name", "compare_doc": "Aadhaar Card"},
            {"key": "father_name", "label": "Father's / Mother's Name",
             "prompt_hi": "पिता या माता का नाम बताइए।",
             "prompt_en": "Father's or mother's name.",
             "high_stakes": True, "compare_to": "father_name", "compare_doc": "Aadhaar Card"},
            {"key": "dob", "label": "Date of Birth",
             "prompt_hi": "जन्म तिथि बताइए।",
             "prompt_en": "Date of birth.",
             "high_stakes": True, "compare_to": "dob", "compare_doc": "Aadhaar Card"},
            {"key": "aadhaar_number", "label": "Aadhaar Number",
             "prompt_hi": "आधार नंबर बताइए।",
             "prompt_en": "Aadhaar number.",
             "high_stakes": True, "compare_to": "id_number", "compare_doc": "Aadhaar Card"},
            {"key": "mobile", "label": "Mobile Number",
             "prompt_hi": "मोबाइल नंबर बताइए।",
             "prompt_en": "Mobile number.",
             "high_stakes": True, "compare_to": None},
            {"key": "certificate_type", "label": "Certificate Type",
             "prompt_hi": "जाति, आय, निवास, या तीनों में से क्या चाहिए?",
             "prompt_en": "Caste, income, domicile, or combination?",
             "high_stakes": True, "compare_to": None},
            {"key": "category", "label": "Caste / Category Claimed",
             "prompt_hi": "दावा की गई जाति या श्रेणी बताइए।",
             "prompt_en": "Caste or category claimed.",
             "high_stakes": True, "compare_to": None},
            {"key": "annual_income", "label": "Annual Family Income (₹)",
             "prompt_hi": "परिवार की सालाना आय कितनी है?",
             "prompt_en": "Annual family income in rupees.",
             "high_stakes": True, "compare_to": None},
            {"key": "address", "label": "Permanent Address with PIN",
             "prompt_hi": "स्थायी पता पिनकोड के साथ बताइए।",
             "prompt_en": "Permanent address with pincode.",
             "high_stakes": True, "compare_to": "address", "compare_doc": "Aadhaar Card"},
            {"key": "purpose", "label": "Purpose (education / scheme / job)",
             "prompt_hi": "प्रमाणपत्र किस काम के लिए चाहिए?",
             "prompt_en": "Purpose — education, scheme, or job?",
             "high_stakes": False, "compare_to": None},
        ],
    },
    "birth_certificate": {
        "id": "birth_certificate",
        "title": "Birth Certificate Application",
        "category": "Municipal / CRS",
        "fill_mode": "paper_or_online",
        "official_form": "CRS Form No. 1 — Birth Report (RBD Act)",
        "source_url": "https://crsorgi.gov.in/web/uploads/download/all_forms_CRS_2019_new.pdf",
        "tagline": "CRS Form 1 still published; portal online in many states; CSC for home births.",
        "why": (
            "ORGI still publishes Form No.1 Birth Report. Central CRS portal covers many States/UTs "
            "online; crsorgi notes CSC login for domiciliary (home) births within 21 days. Child/"
            "parent name and DOB must align across hospital slip and Aadhaar."
        ),
        "required_docs": ["Aadhaar Card"],
        "optional_docs": ["Hospital Discharge", "Ration Card", "School Certificate"],
        "portal": {
            "name": "CRS / State municipal birth registration",
            "url": "https://crsorgi.gov.in",
        },
        "form_fields": [
            {"key": "child_name", "label": "Child's Full Name",
             "prompt_hi": "बच्चे का पूरा नाम बताइए।",
             "prompt_en": "Child's full name.",
             "high_stakes": True, "compare_to": "full_name"},
            {"key": "full_name", "label": "Parent / Informant Name",
             "prompt_hi": "माता-पिता या सूचना देने वाले का नाम बताइए।",
             "prompt_en": "Parent or informant's name.",
             "high_stakes": True, "compare_to": "full_name", "compare_doc": "Aadhaar Card"},
            {"key": "father_name", "label": "Father's Name",
             "prompt_hi": "पिता का नाम बताइए।",
             "prompt_en": "Father's name.",
             "high_stakes": True, "compare_to": "father_name"},
            {"key": "mother_name", "label": "Mother's Name",
             "prompt_hi": "माता का नाम बताइए।",
             "prompt_en": "Mother's name.",
             "high_stakes": True, "compare_to": None},
            {"key": "dob", "label": "Date of Birth of Child",
             "prompt_hi": "बच्चे की जन्म तिथि बताइए।",
             "prompt_en": "Child's date of birth.",
             "high_stakes": True, "compare_to": "dob"},
            {"key": "place_of_birth", "label": "Place of Birth (hospital / home + city)",
             "prompt_hi": "जन्म कहाँ हुआ — अस्पताल या घर, शहर?",
             "prompt_en": "Place of birth — hospital or home, city.",
             "high_stakes": True, "compare_to": None},
            {"key": "aadhaar_number", "label": "Parent Aadhaar Number",
             "prompt_hi": "माता-पिता का आधार नंबर बताइए।",
             "prompt_en": "Parent's Aadhaar number.",
             "high_stakes": True, "compare_to": "id_number", "compare_doc": "Aadhaar Card"},
            {"key": "mobile", "label": "Mobile Number",
             "prompt_hi": "मोबाइल नंबर बताइए।",
             "prompt_en": "Mobile number.",
             "high_stakes": True, "compare_to": None},
            {"key": "address", "label": "Parents' Address with PIN",
             "prompt_hi": "माता-पिता का पता पिनकोड के साथ बताइए।",
             "prompt_en": "Parents' address with pincode.",
             "high_stakes": True, "compare_to": "address", "compare_doc": "Aadhaar Card"},
        ],
    },
    "bank_aadhaar_seed": {
        "id": "bank_aadhaar_seed",
        "title": "Bank Aadhaar Seeding / KYC Update",
        "category": "Banking",
        "fill_mode": "assisted_counter",
        "official_form": "Bank/BC Aadhaar consent + NPCI mapper seeding (not a national ICR form)",
        "source_url": "https://uidai.gov.in/en/309-faqs/direct-benefit-transfer-dbt/about-dbt/12663-how-do-i-receive-benefits-under-the-govt-schemes-in-my-bank-account.html",
        "tagline": "UIDAI: visit branch, fill bank mandate/consent — bank seeds NPCI mapper.",
        "why": (
            "UIDAI DBT FAQ: visit the bank branch and request linking by filling the bank's "
            "mandate and consent form; bank seeds the account on the NPCI mapper. Not a "
            "national ICR form — include because DBT fails when passbook name ≠ Aadhaar."
        ),
        "required_docs": ["Aadhaar Card", "Bank Passbook"],
        "optional_docs": ["PAN Card", "Voter ID"],
        "portal": {
            "name": "Bank branch / BC — NPCI Aadhaar seeding",
            "url": "https://www.npci.org.in",
        },
        "form_fields": [
            {"key": "full_name", "label": "Name as on Bank Account",
             "prompt_hi": "बैंक खाते पर लिखा नाम बताइए।",
             "prompt_en": "Name as printed on the bank account.",
             "high_stakes": True, "compare_to": "full_name", "compare_doc": "Bank Passbook"},
            {"key": "aadhaar_number", "label": "Aadhaar Number to Seed",
             "prompt_hi": "जिस आधार को जोड़ना है वह नंबर बताइए।",
             "prompt_en": "Aadhaar number to seed.",
             "high_stakes": True, "compare_to": "id_number", "compare_doc": "Aadhaar Card"},
            {"key": "account_number", "label": "Bank Account Number",
             "prompt_hi": "बैंक खाता संख्या बताइए।",
             "prompt_en": "Bank account number.",
             "high_stakes": True, "compare_to": "id_number", "compare_doc": "Bank Passbook"},
            {"key": "ifsc", "label": "IFSC Code",
             "prompt_hi": "आईएफएससी कोड बताइए।",
             "prompt_en": "IFSC code.",
             "high_stakes": True, "compare_to": None},
            {"key": "mobile", "label": "Mobile Linked to Account",
             "prompt_hi": "खाते से जुड़ा मोबाइल बताइए।",
             "prompt_en": "Mobile linked to the account.",
             "high_stakes": True, "compare_to": None},
            {"key": "dob", "label": "Date of Birth",
             "prompt_hi": "जन्म तिथि बताइए।",
             "prompt_en": "Date of birth.",
             "high_stakes": True, "compare_to": "dob", "compare_doc": "Aadhaar Card"},
            {"key": "request_type", "label": "Seed / Re-seed / KYC Update",
             "prompt_hi": "सीडिंग, दोबारा सीडिंग, या केवाईसी अपडेट?",
             "prompt_en": "Seed, re-seed, or KYC update?",
             "high_stakes": True, "compare_to": None},
        ],
    },
    # Primary: Dept of Publication — gazette name change still personal/post paper stack
    # https://deptpub.gov.in/document-category/con-guidelines/
    "gazette_name_change": {
        "id": "gazette_name_change",
        "title": "Gazette Name Change (Part IV)",
        "category": "Gazette / Name",
        "fill_mode": "paper_block_letters",
        "official_form": "Change of Name (Adult/Major) — Gazette of India Part IV",
        "source_url": "https://deptpub.gov.in/document-category/con-guidelines/",
        "tagline": "Clearest still-manual identity stack — newspaper, deed, typed proforma, post/person submit.",
        "why": (
            "Department of Publication guidelines: documents submitted personally or by post to "
            "Civil Lines, Delhi — no agents/advocates channel. Needs newspaper notice, "
            "undertaking/deed, computer-typed proforma signed in OLD name with two witnesses, "
            "photos, Bharatkosh fee. Unlocks significant PAN/Aadhaar/passport name changes."
        ),
        "required_docs": ["Aadhaar Card"],
        "optional_docs": ["PAN Card", "Passport", "Voter ID", "Newspaper Cutting"],
        "portal": {
            "name": "Department of Publication / eGazette",
            "url": "https://egazette.gov.in",
        },
        "form_fields": [
            {"key": "full_name", "label": "Present / Old Full Name (as signed on proforma)",
             "prompt_hi": "पुराना पूरा नाम बताइए — जैसा अभी दस्तावेज़ों पर है।",
             "prompt_en": "Present/old full name as currently on documents.",
             "high_stakes": True, "compare_to": "full_name", "compare_doc": "Aadhaar Card"},
            {"key": "new_name", "label": "New Full Name Sought",
             "prompt_hi": "नया पूरा नाम बताइए जो गजट में चाहिए।",
             "prompt_en": "New full name to appear in the gazette.",
             "high_stakes": True, "compare_to": None},
            {"key": "father_name", "label": "Father's / Husband's Name",
             "prompt_hi": "पिता या पति का नाम बताइए।",
             "prompt_en": "Father's or husband's name.",
             "high_stakes": True, "compare_to": "father_name", "compare_doc": "Aadhaar Card"},
            {"key": "dob", "label": "Date of Birth",
             "prompt_hi": "जन्म तिथि बताइए।",
             "prompt_en": "Date of birth.",
             "high_stakes": True, "compare_to": "dob", "compare_doc": "Aadhaar Card"},
            {"key": "aadhaar_number", "label": "Aadhaar Number",
             "prompt_hi": "आधार नंबर बताइए।",
             "prompt_en": "Aadhaar number.",
             "high_stakes": True, "compare_to": "id_number", "compare_doc": "Aadhaar Card"},
            {"key": "mobile", "label": "Mobile Number",
             "prompt_hi": "मोबाइल नंबर बताइए।",
             "prompt_en": "Mobile number.",
             "high_stakes": True, "compare_to": None},
            {"key": "address", "label": "Address with PIN",
             "prompt_hi": "पूरा पता पिनकोड के साथ बताइए।",
             "prompt_en": "Full address with pincode.",
             "high_stakes": True, "compare_to": "address", "compare_doc": "Aadhaar Card"},
            {"key": "reason", "label": "Reason for Name Change",
             "prompt_hi": "नाम बदलने का कारण बताइए।",
             "prompt_en": "Reason for changing the name.",
             "high_stakes": True, "compare_to": None},
            {"key": "newspaper_details", "label": "Newspaper Notice (paper + date)",
             "prompt_hi": "किस अखबार में नोटिस छपा और तारीख?",
             "prompt_en": "Which newspaper carried the notice, and on what date?",
             "high_stakes": True, "compare_to": None},
        ],
    },
    # Primary: Protean Form 49A — online fill still often means print ack + physical proofs by post/CSC
    "pan_new_49a": {
        "id": "pan_new_49a",
        "title": "New PAN — Form 49A",
        "category": "Tax / PAN",
        "fill_mode": "paper_or_online",
        "official_form": "Form 49A — Application for Allotment of PAN (Individual)",
        "source_url": "https://tin.tin.nsdl.com/pan/form49ACombine.html",
        "tagline": "Online fill → print signed ack → physical POI/POA/DOB proofs (or CSC lane).",
        "why": (
            "Protean/UTIITSL Form 49A: do’s still say block letters in English; after online "
            "fill, signed acknowledgment plus physical proofs are commonly posted or handled "
            "via CSC. Name on application must match POI/POA/PODB exactly — same mismatch "
            "class as Aadhaar."
        ),
        "required_docs": ["Aadhaar Card"],
        "optional_docs": ["Bank Passbook", "Voter ID", "Passport", "Ration Card"],
        "portal": {
            "name": "Protean / UTIITSL — Apply for New PAN",
            "url": "https://www.onlineservices.nsdl.com/paam/endUserRegisterContact.html",
        },
        "form_fields": [
            {"key": "full_name", "label": "Full Name (no titles; as on POI)",
             "prompt_hi": "पूरा नाम बताइए जैसा पहचान पत्र पर है — उपाधि न लगाएँ।",
             "prompt_en": "Full name as on proof of identity, without titles.",
             "high_stakes": True, "compare_to": "full_name", "compare_doc": "Aadhaar Card"},
            {"key": "father_name", "label": "Father's Name",
             "prompt_hi": "पिता का नाम बताइए।",
             "prompt_en": "Father's name.",
             "high_stakes": True, "compare_to": "father_name", "compare_doc": "Aadhaar Card"},
            {"key": "dob", "label": "Date of Birth",
             "prompt_hi": "जन्म तिथि बताइए।",
             "prompt_en": "Date of birth.",
             "high_stakes": True, "compare_to": "dob", "compare_doc": "Aadhaar Card"},
            {"key": "aadhaar_number", "label": "Aadhaar Number",
             "prompt_hi": "आधार नंबर बताइए।",
             "prompt_en": "Aadhaar number.",
             "high_stakes": True, "compare_to": "id_number", "compare_doc": "Aadhaar Card"},
            {"key": "mobile", "label": "Mobile Number",
             "prompt_hi": "मोबाइल नंबर बताइए।",
             "prompt_en": "Mobile number.",
             "high_stakes": True, "compare_to": None},
            {"key": "email", "label": "Email Address",
             "prompt_hi": "ईमेल पता बताइए।",
             "prompt_en": "Email address.",
             "high_stakes": True, "compare_to": None},
            {"key": "address", "label": "Address for Communication (with PIN)",
             "prompt_hi": "पत्राचार का पता पिनकोड के साथ बताइए।",
             "prompt_en": "Communication address with pincode.",
             "high_stakes": True, "compare_to": "address", "compare_doc": "Aadhaar Card"},
            {"key": "name_on_card", "label": "Name to Print on PAN Card",
             "prompt_hi": "पैन कार्ड पर कौन सा नाम छपे — पूरा या संक्षिप्त?",
             "prompt_en": "Name to print on the PAN card — full or abbreviated?",
             "high_stakes": True, "compare_to": "full_name", "compare_doc": "Aadhaar Card"},
        ],
    },
}


def get_service(service_id: str) -> dict:
    return SERVICES[service_id]


def list_services() -> list[dict]:
    return list(SERVICES.values())
