import type { Service } from "@/lib/api/identitygraph";

/** Mirrors Sarvam_AI/identitygraph/services.py — desk loads live catalog from API. */
export const SERVICES: Service[] = [
  {
    id: "link_mobile_aadhaar",
    title: "Aadhaar Form 1 — Enrolment / Demographic Update",
    category: "Aadhaar",
    fill_mode: "paper_block_letters",
    official_form: "UIDAI Form 1: Aadhaar Enrolment and Update",
    source_url: "https://uidai.gov.in/images/Form_1_Eng.pdf",
    tagline: "Official ASK paper form — BLOCK LETTERS; fill only fields being updated.",
    why: "UIDAI Form 1 is still the counter form at Aadhaar Seva Kendras. Instructions: use only upper-case (block/capital) letters; for updates fill only fields to change (name, gender, DOB, address, mobile, email). Name must match POI without titles. Operator/citizen transcription errors here break OTP and every downstream KYC.",
    required_docs: ["Aadhaar Card"],
    optional_docs: ["PAN Card", "Bank Passbook", "Voter ID", "Ration Card"],
    portal: {
      name: "Aadhaar Seva Kendra / myAadhaar",
      url: "https://myaadhaar.uidai.gov.in",
    },
    form_fields: [
      {"key": "update_fields", "label": "Fields to Update (name/DOB/address/mobile/email/gender)", "high_stakes": true, "compare_to": null, "prompt_hi": "आधार में क्या अपडेट करना है — नाम, जन्म तिथि, पता, मोबाइल, ईमेल, लिंग?", "prompt_en": "What to update on Aadhaar — name, DOB, address, mobile, email, gender?"},
      {"key": "full_name", "label": "Full Name (as on POI, no titles)", "high_stakes": true, "compare_to": "full_name", "compare_doc": "Aadhaar Card", "prompt_hi": "पूरा नाम बताइए जैसा पहचान पत्र पर है — श्री/श्रीमती न लगाएँ।", "prompt_en": "Full name as on proof of identity, omitting titles."},
      {"key": "dob", "label": "Date of Birth", "high_stakes": true, "compare_to": "dob", "compare_doc": "Aadhaar Card", "prompt_hi": "जन्म तिथि बताइए — दिन, महीना, साल।", "prompt_en": "Date of birth — day, month, year."},
      {"key": "aadhaar_number", "label": "Aadhaar Number (for update)", "high_stakes": true, "compare_to": "id_number", "compare_doc": "Aadhaar Card", "prompt_hi": "बारह अंकों का आधार नंबर बताइए।", "prompt_en": "Twelve-digit Aadhaar number."},
      {"key": "mobile", "label": "Mobile Number", "high_stakes": true, "compare_to": null, "prompt_hi": "मोबाइल नंबर बताइए।", "prompt_en": "Mobile number."},
      {"key": "email", "label": "Email (if updating)", "high_stakes": false, "compare_to": null, "prompt_hi": "ईमेल अगर अपडेट करना है तो बताइए।", "prompt_en": "Email if updating."},
      {"key": "gender", "label": "Gender", "high_stakes": false, "compare_to": null, "prompt_hi": "लिंग बताइए — पुरुष, महिला या अन्य।", "prompt_en": "Gender — male, female, or third gender."},
      {"key": "address", "label": "Address (PIN + post office mandatory on Form 1)", "high_stakes": true, "compare_to": "address", "compare_doc": "Aadhaar Card", "prompt_hi": "पूरा पता बताइए — पिनकोड और पोस्ट ऑफिस ज़रूर।", "prompt_en": "Full address — pincode and post office are mandatory on Form 1."},
    ],
  },
  {
    id: "rto_dl_update",
    title: "RTO — Driving Licence Address / Name Update",
    category: "Transport",
    fill_mode: "assisted_counter",
    official_form: "CMVR Form 2 / Sarathi Services on DL",
    source_url: "https://parivahan.gov.in/en/node/246",
    tagline: "Sarathi online apply + RTO counter with originals — Form 2 still published.",
    why: "MoRTH/Parivahan says change of address is applied ONLINE on Sarathi, then citizen visits RTO with originals. CMVR Form 2 (learner/DL/renewal/change of address or name) is still published as a downloadable form. CSC desks commonly type from DL + Aadhaar; wrong DL number or address without pincode still rejects.",
    required_docs: ["Driving License", "Aadhaar Card"],
    optional_docs: ["PAN Card", "Bank Passbook", "Ration Card"],
    portal: {
      name: "Parivahan Sarathi — Change of Address / Name in DL",
      url: "https://sarathi.parivahan.gov.in",
    },
    form_fields: [
      {"key": "full_name", "label": "Full Name", "high_stakes": true, "compare_to": "full_name", "prompt_hi": "अपना पूरा नाम बताइए।", "prompt_en": "Please say your full name."},
      {"key": "father_name", "label": "Father's / Guardian's Name", "high_stakes": true, "compare_to": "father_name", "compare_doc": "Aadhaar Card", "prompt_hi": "अपने पिता या अभिभावक का नाम बताइए।", "prompt_en": "Please say your father's or guardian's name."},
      {"key": "dl_number", "label": "Driving Licence Number", "high_stakes": false, "compare_to": "id_number", "compare_doc": "Driving License", "prompt_hi": "अपना ड्राइविंग लाइसेंस नंबर बताइए।", "prompt_en": "Please say your driving licence number."},
      {"key": "pan_number", "label": "PAN Number", "high_stakes": false, "compare_to": "id_number", "compare_doc": "PAN Card", "prompt_hi": "दस अक्षर का पैन नंबर बताइए।", "prompt_en": "Ten-character PAN number."},
      {"key": "dob", "label": "Date of Birth", "high_stakes": true, "compare_to": "dob", "prompt_hi": "अपनी जन्म तिथि बताइए।", "prompt_en": "Please say your date of birth."},
      {"key": "mobile", "label": "Mobile Number", "high_stakes": false, "compare_to": null, "prompt_hi": "अपना मोबाइल नंबर बताइए।", "prompt_en": "Please say your mobile number."},
      {"key": "change_type", "label": "What to Change", "high_stakes": false, "compare_to": null, "prompt_hi": "आप क्या बदलना चाहते हैं — नाम, पता, या दोनों?", "prompt_en": "What do you want to change — name, address, or both?"},
      {"key": "old_address", "label": "Address on Current DL", "high_stakes": false, "compare_to": "address", "compare_doc": "Driving License", "prompt_hi": "लाइसेंस पर अभी कौन सा पता लिखा है?", "prompt_en": "What address is currently printed on your licence?"},
      {"key": "new_address", "label": "New Address (with pincode)", "high_stakes": true, "compare_to": "address", "compare_doc": "Aadhaar Card", "prompt_hi": "नया पता बताइए — पिनकोड ज़रूर बताएं।", "prompt_en": "Please say your new address, including pincode."},
    ],
  },
  {
    id: "scheme_apply",
    title: "Gov Scheme Discovery + Darkhast (Application)",
    category: "Schemes",
    fill_mode: "assisted_counter",
    official_form: "Scheme-specific CSC / myScheme application (varies by scheme)",
    source_url: "https://www.myscheme.gov.in",
    tagline: "CSC-assisted portal fill — identity + income/category mismatch kills DBT.",
    why: "Not one national paper form — CSC operators still fill PM-KISAN / Ayushman / e-Shram portals from Aadhaar + ration + passbook. Applications bounce on income/category/Aadhaar-mobile mismatch more than on missing checkboxes.",
    required_docs: ["Aadhaar Card", "Ration Card"],
    optional_docs: ["Bank Passbook", "School Certificate"],
    portal: {
      name: "National / State scheme portals (via CSC)",
      url: "https://www.myscheme.gov.in",
    },
    form_fields: [
      {"key": "full_name", "label": "Applicant Full Name", "high_stakes": true, "compare_to": "full_name", "prompt_hi": "आवेदक का पूरा नाम बताइए।", "prompt_en": "Please say the applicant's full name."},
      {"key": "aadhaar_number", "label": "Aadhaar Number", "high_stakes": true, "compare_to": "id_number", "compare_doc": "Aadhaar Card", "prompt_hi": "आधार नंबर बताइए।", "prompt_en": "Please say the Aadhaar number."},
      {"key": "dob", "label": "Date of Birth", "high_stakes": true, "compare_to": "dob", "prompt_hi": "जन्म तिथि बताइए।", "prompt_en": "Please say date of birth."},
      {"key": "mobile", "label": "Mobile (Aadhaar-linked)", "high_stakes": true, "compare_to": null, "prompt_hi": "आधार से जुड़ा मोबाइल नंबर बताइए।", "prompt_en": "Please say the Aadhaar-linked mobile number."},
      {"key": "address", "label": "Address with pincode", "high_stakes": true, "compare_to": "address", "prompt_hi": "पूरा पता पिनकोड के साथ बताइए।", "prompt_en": "Please say full address with pincode."},
      {"key": "scheme_name", "label": "Scheme Name", "high_stakes": true, "compare_to": null, "prompt_hi": "कौन सी योजना के लिए आवेदन करना है? जैसे पीएम किसान, आयुष्मान, ई-श्रम।", "prompt_en": "Which scheme? e.g. PM-KISAN, Ayushman, e-Shram."},
      {"key": "category", "label": "Category (SC/ST/OBC/EWS/General)", "high_stakes": true, "compare_to": null, "prompt_hi": "आपकी श्रेणी क्या है — अनुसूचित जाति, जनजाति, ओबीसी, ईडब्ल्यूएस या सामान्य?", "prompt_en": "What is your category — SC, ST, OBC, EWS, or General?"},
      {"key": "annual_income", "label": "Approx Annual Family Income (₹)", "high_stakes": true, "compare_to": null, "prompt_hi": "परिवार की सालाना आय लगभग कितनी है?", "prompt_en": "What is approximate annual family income in rupees?"},
    ],
  },
  {
    id: "grievance_complaint",
    title: "File a Government Service Complaint",
    category: "Grievance",
    fill_mode: "portal_identity",
    official_form: "CPGRAMS / state public grievance",
    source_url: "https://pgportal.gov.in",
    tagline: "Online grievance — desk value is factual capture, not paper ICR.",
    why: "CPGRAMS is online. Include only because rejected Aadhaar/RTO/scheme cases need a clean factual complaint with identity refs; vague filings get closed.",
    required_docs: ["Aadhaar Card"],
    optional_docs: ["Rejection letter", "Acknowledgement receipt"],
    portal: {
      name: "CPGRAMS / State public grievance portal",
      url: "https://pgportal.gov.in",
    },
    form_fields: [
      {"key": "full_name", "label": "Full Name", "high_stakes": true, "compare_to": "full_name", "prompt_hi": "अपना नाम बताइए।", "prompt_en": "Please say your name."},
      {"key": "mobile", "label": "Mobile", "high_stakes": true, "compare_to": null, "prompt_hi": "मोबाइल नंबर बताइए।", "prompt_en": "Please say your mobile number."},
      {"key": "aadhaar_number", "label": "Aadhaar Number", "high_stakes": true, "compare_to": "id_number", "compare_doc": "Aadhaar Card", "prompt_hi": "आधार नंबर बताइए।", "prompt_en": "Please say your Aadhaar number."},
      {"key": "department", "label": "Department / Office", "high_stakes": true, "compare_to": null, "prompt_hi": "किस विभाग या दफ्तर से शिकायत है — आधार, आरटीओ, योजना?", "prompt_en": "Which department — Aadhaar, RTO, scheme office?"},
      {"key": "complaint_summary", "label": "What Happened (facts)", "high_stakes": true, "compare_to": null, "prompt_hi": "क्या समस्या हुई — तारीख और संदर्भ नंबर के साथ बताइए।", "prompt_en": "What went wrong — include dates and any reference number."},
      {"key": "desired_outcome", "label": "What You Want Done", "high_stakes": true, "compare_to": null, "prompt_hi": "आप क्या चाहते हैं — सुधार, स्टेटस, या दोबारा आवेदन?", "prompt_en": "What outcome do you want — correction, status, or re-apply?"},
    ],
  },
  {
    id: "pan_aadhaar_link",
    title: "Link PAN with Aadhaar",
    category: "Tax / PAN",
    fill_mode: "portal_identity",
    official_form: "Income-tax e-Filing — Link Aadhaar (online)",
    source_url: "https://eportal.incometax.gov.in",
    tagline: "Online link — desk value is name/DOB match; fix via PAN CR if it fails.",
    why: "Linking itself is online on the e-Filing portal — not a block-letter paper form. Keep on the desk because Mohd/Mohammed-style mismatches fail the link; remediation is usually PAN Change Request (paper/online), not retrying the link.",
    required_docs: ["Aadhaar Card", "PAN Card"],
    optional_docs: ["Bank Passbook"],
    portal: {
      name: "Income Tax e-Filing — Link Aadhaar",
      url: "https://eportal.incometax.gov.in",
    },
    form_fields: [
      {"key": "full_name", "label": "Full Name (as on PAN)", "high_stakes": true, "compare_to": "full_name", "compare_doc": "PAN Card", "prompt_hi": "पैन पर लिखा पूरा नाम बताइए।", "prompt_en": "Full name as on PAN."},
      {"key": "pan_number", "label": "PAN Number", "high_stakes": true, "compare_to": "id_number", "compare_doc": "PAN Card", "prompt_hi": "दस अक्षर का पैन नंबर बताइए।", "prompt_en": "Ten-character PAN number."},
      {"key": "aadhaar_number", "label": "Aadhaar Number", "high_stakes": true, "compare_to": "id_number", "compare_doc": "Aadhaar Card", "prompt_hi": "आधार नंबर बताइए।", "prompt_en": "Aadhaar number."},
      {"key": "dob", "label": "Date of Birth", "high_stakes": true, "compare_to": "dob", "compare_doc": "PAN Card", "prompt_hi": "जन्म तिथि बताइए।", "prompt_en": "Date of birth."},
      {"key": "mobile", "label": "Registered Mobile", "high_stakes": true, "compare_to": null, "prompt_hi": "रजिस्टर्ड मोबाइल बताइए।", "prompt_en": "Registered mobile."},
    ],
  },
  {
    id: "voter_form8",
    title: "Voter ID — Form 8 (Correction / Shift / EPIC)",
    category: "Elections",
    fill_mode: "paper_or_online",
    official_form: "ECI Form 8 (Registration of Electors Rules, 1960)",
    source_url: "https://voters.eci.gov.in/formspdf/Form_8_English.pdf",
    tagline: "Statutory Form 8 — online OR free paper at BLO/ERO; photo paste on print.",
    why: "ECI still offers offline Form 8 free at ERO/AERO/BLO offices (also online on VSP). Paper path: print PDF, paste passport photo, self-attest proofs, hand to BLO or post to ERO. Name/DOB/address vs Aadhaar/EPIC mismatches are classic rejections.",
    required_docs: ["Aadhaar Card", "Voter ID"],
    optional_docs: ["Ration Card", "Bank Passbook", "Electricity Bill"],
    portal: {
      name: "Voters' Services Portal — Form 8",
      url: "https://voters.eci.gov.in",
    },
    form_fields: [
      {"key": "full_name", "label": "Full Name (as in electoral roll)", "high_stakes": true, "compare_to": "full_name", "compare_doc": "Voter ID", "prompt_hi": "मतदाता सूची में लिखा पूरा नाम बताइए।", "prompt_en": "Full name as in the electoral roll."},
      {"key": "epic_number", "label": "EPIC / Voter ID Number", "high_stakes": true, "compare_to": "id_number", "compare_doc": "Voter ID", "prompt_hi": "अपना वोटर आईडी या ईपीआईसी नंबर बताइए।", "prompt_en": "Please say your EPIC / voter ID number."},
      {"key": "dob", "label": "Date of Birth / Age", "high_stakes": true, "compare_to": "dob", "compare_doc": "Aadhaar Card", "prompt_hi": "जन्म तिथि या आयु बताइए।", "prompt_en": "Date of birth or age on the roll."},
      {"key": "aadhaar_number", "label": "Aadhaar Number", "high_stakes": true, "compare_to": "id_number", "compare_doc": "Aadhaar Card", "prompt_hi": "आधार नंबर बताइए।", "prompt_en": "Aadhaar number."},
      {"key": "mobile", "label": "Mobile Number", "high_stakes": true, "compare_to": null, "prompt_hi": "मोबाइल नंबर बताइए।", "prompt_en": "Mobile number."},
      {"key": "request_type", "label": "Request Type", "high_stakes": true, "compare_to": null, "prompt_hi": "क्या करना है — नाम/पता सुधार, निवास स्थान बदलाव, या नया ईपीआईसी?", "prompt_en": "Correction, shift of residence, or EPIC replacement?"},
      {"key": "correction_fields", "label": "What to Correct (max 4)", "high_stakes": true, "compare_to": null, "prompt_hi": "कौन सी प्रविष्टियाँ गलत हैं — नाम, जन्म तिथि, पता, फोटो?", "prompt_en": "Which entries to fix — name, DOB, address, photo?"},
      {"key": "new_address", "label": "Correct / New Address (with PIN)", "high_stakes": true, "compare_to": "address", "compare_doc": "Aadhaar Card", "prompt_hi": "सही या नया पता पिनकोड के साथ बताइए।", "prompt_en": "Correct or new address including pincode."},
      {"key": "father_name", "label": "Relation Name (Father/Mother/Spouse)", "high_stakes": false, "compare_to": "father_name", "compare_doc": "Aadhaar Card", "prompt_hi": "पिता, माता या पति/पत्नी का नाम बताइए।", "prompt_en": "Father's, mother's, or spouse's name."},
    ],
  },
  {
    id: "voter_form6",
    title: "Voter ID — Form 6 (New Enrolment)",
    category: "Elections",
    fill_mode: "paper_or_online",
    official_form: "ECI Form 6 — Application Form for New Voters",
    source_url: "https://voters.eci.gov.in/formspdf/Form_6_English.pdf",
    tagline: "Form 6 — English name in BLOCK LETTERS; offline at BLO still valid.",
    why: "ECI Form 6 PDF requires name in English in BLOCK LETTERS and a pasted photograph. Official FAQ: enrol offline — form free at ERO/AERO/BLO; file in person, by post, or hand to BLO. Aadhaar demographic mismatch is a top rejection reason.",
    required_docs: ["Aadhaar Card"],
    optional_docs: ["Ration Card", "School Certificate", "Birth Certificate"],
    portal: {
      name: "Voters' Services Portal — Form 6",
      url: "https://voters.eci.gov.in",
    },
    form_fields: [
      {"key": "full_name", "label": "Applicant Full Name", "high_stakes": true, "compare_to": "full_name", "compare_doc": "Aadhaar Card", "prompt_hi": "आवेदक का पूरा नाम बताइए।", "prompt_en": "Applicant's full name."},
      {"key": "father_name", "label": "Father's / Mother's / Husband's Name", "high_stakes": true, "compare_to": "father_name", "compare_doc": "Aadhaar Card", "prompt_hi": "पिता, माता या पति का नाम बताइए।", "prompt_en": "Father's, mother's, or husband's name."},
      {"key": "dob", "label": "Date of Birth", "high_stakes": true, "compare_to": "dob", "compare_doc": "Aadhaar Card", "prompt_hi": "जन्म तिथि बताइए।", "prompt_en": "Date of birth."},
      {"key": "aadhaar_number", "label": "Aadhaar Number", "high_stakes": true, "compare_to": "id_number", "compare_doc": "Aadhaar Card", "prompt_hi": "आधार नंबर बताइए।", "prompt_en": "Aadhaar number."},
      {"key": "mobile", "label": "Mobile Number", "high_stakes": true, "compare_to": null, "prompt_hi": "मोबाइल नंबर बताइए।", "prompt_en": "Mobile number."},
      {"key": "gender", "label": "Gender", "high_stakes": true, "compare_to": null, "prompt_hi": "लिंग बताइए — पुरुष, महिला या अन्य।", "prompt_en": "Gender — male, female, or other."},
      {"key": "address", "label": "Ordinary Residence Address (with PIN)", "high_stakes": true, "compare_to": "address", "compare_doc": "Aadhaar Card", "prompt_hi": "साधारण निवास का पूरा पता पिनकोड के साथ बताइए।", "prompt_en": "Ordinary residence address with pincode."},
      {"key": "assembly_constituency", "label": "Assembly Constituency (if known)", "high_stakes": false, "compare_to": null, "prompt_hi": "विधानसभा क्षेत्र का नाम अगर पता हो तो बताइए।", "prompt_en": "Assembly constituency name if known."},
    ],
  },
  {
    id: "passport_apply",
    title: "Passport Application (CSC / PSK Assisted)",
    category: "Passport",
    fill_mode: "paper_block_letters",
    official_form: "Passport Application + Supplementary Form (ICR) / Annexures",
    source_url: "https://www.passportindia.gov.in/AppOnlineProject/pdf/ApplicationformInstructionBooklet-V3.0.pdf",
    tagline: "Official instructions: CAPITAL LETTERS, ball-point, ICR scan; annexures on plain/stamp paper.",
    why: "Passport Seva instruction booklet: form is machine-readable for ICR scanners; use CAPITAL LETTERS only; black/blue ball-point; leave blank box between words. CSC/DPC path still pastes photograph. Annexures C/D/K etc. are specimen declarations on plain paper or non-judicial stamp paper — filled by hand. Given name/surname/DOB must match Aadhaar or old passport.",
    required_docs: ["Aadhaar Card"],
    optional_docs: ["PAN Card", "Voter ID", "Bank Passbook", "Old Passport"],
    portal: {
      name: "Passport Seva — Fresh / Re-issue",
      url: "https://www.passportindia.gov.in",
    },
    form_fields: [
      {"key": "full_name", "label": "Given Name + Surname (as on Aadhaar)", "high_stakes": true, "compare_to": "full_name", "compare_doc": "Aadhaar Card", "prompt_hi": "आधार जैसा पूरा नाम — नाम और सरनेम अलग-अलग बताइए।", "prompt_en": "Given name and surname exactly as on Aadhaar."},
      {"key": "father_name", "label": "Father's / Legal Guardian's Name", "high_stakes": true, "compare_to": "father_name", "compare_doc": "Aadhaar Card", "prompt_hi": "पिता या अभिभावक का नाम बताइए।", "prompt_en": "Father's or legal guardian's name."},
      {"key": "dob", "label": "Date of Birth", "high_stakes": true, "compare_to": "dob", "compare_doc": "Aadhaar Card", "prompt_hi": "जन्म तिथि बताइए।", "prompt_en": "Date of birth."},
      {"key": "place_of_birth", "label": "Place of Birth (village/town + district + state)", "high_stakes": true, "compare_to": null, "prompt_hi": "जन्म स्थान — गाँव/शहर, ज़िला, राज्य बताइए।", "prompt_en": "Place of birth — town, district, state."},
      {"key": "aadhaar_number", "label": "Aadhaar Number", "high_stakes": true, "compare_to": "id_number", "compare_doc": "Aadhaar Card", "prompt_hi": "आधार नंबर बताइए।", "prompt_en": "Aadhaar number."},
      {"key": "mobile", "label": "Mobile Number", "high_stakes": true, "compare_to": null, "prompt_hi": "मोबाइल नंबर बताइए।", "prompt_en": "Mobile number."},
      {"key": "email", "label": "Email Address", "high_stakes": true, "compare_to": null, "prompt_hi": "ईमेल पता बताइए।", "prompt_en": "Email address."},
      {"key": "address", "label": "Present Address (with PIN)", "high_stakes": true, "compare_to": "address", "compare_doc": "Aadhaar Card", "prompt_hi": "वर्तमान पता पिनकोड के साथ बताइए।", "prompt_en": "Present address with pincode."},
      {"key": "service_type", "label": "Fresh Passport or Re-issue", "high_stakes": true, "compare_to": null, "prompt_hi": "नया पासपोर्ट चाहिए या पुराना बदलना है?", "prompt_en": "Fresh passport or re-issue?"},
      {"key": "old_passport_number", "label": "Old Passport Number (if re-issue)", "high_stakes": false, "compare_to": "id_number", "compare_doc": "Old Passport", "prompt_hi": "अगर पुराना पासपोर्ट है तो नंबर बताइए।", "prompt_en": "Old passport number if re-issuing."},
    ],
  },
  {
    id: "pan_correction",
    title: "PAN Correction / Change Request",
    category: "Tax / PAN",
    fill_mode: "paper_block_letters",
    official_form: "Request for New PAN Card Or/And Changes or Correction in PAN Data (PAN CR)",
    source_url: "https://incometaxindia.gov.in/Documents/form-for-changes-in-pan.pdf",
    tagline: "ITD/Protean/UTIITSL — BLOCK LETTERS physical OR online; print+post proofs common.",
    why: "DGIT (Systems): PAN CR forms can be submitted physically at UTIITSL/Protean centres or online. Instructions: BLOCK LETTERS, preferably black ink, English only; tick left-margin boxes for fields being corrected. Protean online path still often needs signed acknowledgment + physical proofs. Real fix when Aadhaar↔PAN link fails.",
    required_docs: ["PAN Card", "Aadhaar Card"],
    optional_docs: ["Birth Certificate", "Gazette Notification", "Marriage Certificate"],
    portal: {
      name: "Protean / UTIITSL — PAN Change Request",
      url: "https://www.onlineservices.nsdl.com/paam/endUserRegisterContact.html",
    },
    form_fields: [
      {"key": "full_name", "label": "Correct Full Name (no titles)", "high_stakes": true, "compare_to": "full_name", "compare_doc": "Aadhaar Card", "prompt_hi": "सही पूरा नाम बताइए — श्री/श्रीमती न लगाएँ।", "prompt_en": "Correct full name without titles like Shri/Smt."},
      {"key": "pan_number", "label": "Existing PAN Number", "high_stakes": true, "compare_to": "id_number", "compare_doc": "PAN Card", "prompt_hi": "मौजूदा पैन नंबर बताइए।", "prompt_en": "Existing PAN number."},
      {"key": "father_name", "label": "Father's Name (as to be printed)", "high_stakes": true, "compare_to": "father_name", "compare_doc": "Aadhaar Card", "prompt_hi": "पिता का नाम बताइए जैसा पैन पर चाहिए।", "prompt_en": "Father's name as it should appear on PAN."},
      {"key": "dob", "label": "Correct Date of Birth", "high_stakes": true, "compare_to": "dob", "compare_doc": "Aadhaar Card", "prompt_hi": "सही जन्म तिथि बताइए।", "prompt_en": "Correct date of birth."},
      {"key": "aadhaar_number", "label": "Aadhaar Number", "high_stakes": true, "compare_to": "id_number", "compare_doc": "Aadhaar Card", "prompt_hi": "आधार नंबर बताइए।", "prompt_en": "Aadhaar number."},
      {"key": "mobile", "label": "Mobile Number", "high_stakes": true, "compare_to": null, "prompt_hi": "मोबाइल नंबर बताइए।", "prompt_en": "Mobile number."},
      {"key": "fields_to_correct", "label": "Fields Being Corrected", "high_stakes": true, "compare_to": null, "prompt_hi": "क्या सुधारना है — नाम, पिता का नाम, जन्म तिथि, पता?", "prompt_en": "What are you correcting — name, father's name, DOB, address?"},
      {"key": "address", "label": "Address on PAN (with PIN)", "high_stakes": false, "compare_to": "address", "compare_doc": "Aadhaar Card", "prompt_hi": "पैन पर दर्ज पता पिनकोड के साथ बताइए।", "prompt_en": "Address for PAN with pincode."},
    ],
  },
  {
    id: "ration_card_update",
    title: "Ration Card — New / Member Add / Correction",
    category: "Food / Ration",
    fill_mode: "assisted_counter",
    official_form: "State Food & Civil Supplies / NFSA e-KYC application (state portal)",
    source_url: "https://nfsa.gov.in",
    tagline: "State portals via CSC — operator-filled; Aadhaar e-KYC name match is the blocker.",
    why: "No single national paper ICR form — NFSA/state food portals are filled at CSC/FPS from Aadhaar + ration booklet. Head-of-family name/DOB mismatches fail e-KYC. Include as assisted-counter identity work, not as a block-letter national form.",
    required_docs: ["Aadhaar Card"],
    optional_docs: ["Ration Card", "Bank Passbook", "Electricity Bill", "Voter ID"],
    portal: {
      name: "State Food & Civil Supplies / NFSA (via CSC)",
      url: "https://nfsa.gov.in",
    },
    form_fields: [
      {"key": "full_name", "label": "Applicant / Head of Family Name", "high_stakes": true, "compare_to": "full_name", "compare_doc": "Aadhaar Card", "prompt_hi": "आवेदक या परिवार मुखिया का नाम बताइए।", "prompt_en": "Applicant or head-of-family name."},
      {"key": "ration_card_number", "label": "Existing Ration Card Number (or NEW)", "high_stakes": true, "compare_to": "id_number", "compare_doc": "Ration Card", "prompt_hi": "राशन कार्ड नंबर बताइए, या नया कार्ड हो तो NEW कहिए।", "prompt_en": "Existing ration card number, or say NEW."},
      {"key": "aadhaar_number", "label": "Aadhaar Number", "high_stakes": true, "compare_to": "id_number", "compare_doc": "Aadhaar Card", "prompt_hi": "आधार नंबर बताइए।", "prompt_en": "Aadhaar number."},
      {"key": "dob", "label": "Date of Birth", "high_stakes": true, "compare_to": "dob", "compare_doc": "Aadhaar Card", "prompt_hi": "जन्म तिथि बताइए।", "prompt_en": "Date of birth."},
      {"key": "mobile", "label": "Mobile (OTP)", "high_stakes": true, "compare_to": null, "prompt_hi": "ओटीपी वाला मोबाइल नंबर बताइए।", "prompt_en": "Mobile number for OTP."},
      {"key": "request_type", "label": "Request Type", "high_stakes": true, "compare_to": null, "prompt_hi": "नया कार्ड, सदस्य जोड़ना, नाम सुधार, या पता बदलाव?", "prompt_en": "New card, add member, name fix, or address change?"},
      {"key": "card_type", "label": "Card Type (AAY / PHH / State)", "high_stakes": true, "compare_to": null, "prompt_hi": "कार्ड प्रकार — अंत्योदय, प्राथमिक, या राज्य का प्रकार?", "prompt_en": "Card type — AAY, PHH, or state category?"},
      {"key": "address", "label": "Address with pincode", "high_stakes": true, "compare_to": "address", "compare_doc": "Aadhaar Card", "prompt_hi": "पूरा पता पिनकोड के साथ बताइए।", "prompt_en": "Full address with pincode."},
      {"key": "family_members", "label": "Family Members Being Added/Corrected", "high_stakes": false, "compare_to": null, "prompt_hi": "जिन सदस्यों को जोड़ना या सुधारना है उनके नाम बताइए।", "prompt_en": "Names of members being added or corrected."},
    ],
  },
  {
    id: "caste_income_certificate",
    title: "Caste / Income / Domicile Certificate",
    category: "Tehsil / Setu",
    fill_mode: "paper_or_online",
    official_form: "State application + caste affidavit (e.g. MH Form 2 / Form 3)",
    source_url: "https://rd.mahaonline.gov.in/PDF/CasteAffidavit_FORM-2.pdf",
    tagline: "e-District online + mandatory handwritten affidavits (MH Form 2/3 verified).",
    why: "Maharashtra Aaple Sarkar lists Affidavit Form-2 and Form-3 as mandatory for caste certificate — blank-line affidavits signed on paper with genealogy. Online filing exists; the affidavit layer is still longhand. Name spelling across Aadhaar/ration/school TC decides approval.",
    required_docs: ["Aadhaar Card", "Ration Card"],
    optional_docs: ["School Certificate", "Property Tax Receipt", "Bank Passbook"],
    portal: {
      name: "State e-District / Setu / CSC certificate services",
      url: "https://www.india.gov.in",
    },
    form_fields: [
      {"key": "full_name", "label": "Applicant Full Name", "high_stakes": true, "compare_to": "full_name", "compare_doc": "Aadhaar Card", "prompt_hi": "आवेदक का पूरा नाम बताइए।", "prompt_en": "Applicant's full name."},
      {"key": "father_name", "label": "Father's / Mother's Name", "high_stakes": true, "compare_to": "father_name", "compare_doc": "Aadhaar Card", "prompt_hi": "पिता या माता का नाम बताइए।", "prompt_en": "Father's or mother's name."},
      {"key": "dob", "label": "Date of Birth", "high_stakes": true, "compare_to": "dob", "compare_doc": "Aadhaar Card", "prompt_hi": "जन्म तिथि बताइए।", "prompt_en": "Date of birth."},
      {"key": "aadhaar_number", "label": "Aadhaar Number", "high_stakes": true, "compare_to": "id_number", "compare_doc": "Aadhaar Card", "prompt_hi": "आधार नंबर बताइए।", "prompt_en": "Aadhaar number."},
      {"key": "mobile", "label": "Mobile Number", "high_stakes": true, "compare_to": null, "prompt_hi": "मोबाइल नंबर बताइए।", "prompt_en": "Mobile number."},
      {"key": "certificate_type", "label": "Certificate Type", "high_stakes": true, "compare_to": null, "prompt_hi": "जाति, आय, निवास, या तीनों में से क्या चाहिए?", "prompt_en": "Caste, income, domicile, or combination?"},
      {"key": "category", "label": "Caste / Category Claimed", "high_stakes": true, "compare_to": null, "prompt_hi": "दावा की गई जाति या श्रेणी बताइए।", "prompt_en": "Caste or category claimed."},
      {"key": "annual_income", "label": "Annual Family Income (₹)", "high_stakes": true, "compare_to": null, "prompt_hi": "परिवार की सालाना आय कितनी है?", "prompt_en": "Annual family income in rupees."},
      {"key": "address", "label": "Permanent Address with PIN", "high_stakes": true, "compare_to": "address", "compare_doc": "Aadhaar Card", "prompt_hi": "स्थायी पता पिनकोड के साथ बताइए।", "prompt_en": "Permanent address with pincode."},
      {"key": "purpose", "label": "Purpose (education / scheme / job)", "high_stakes": false, "compare_to": null, "prompt_hi": "प्रमाणपत्र किस काम के लिए चाहिए?", "prompt_en": "Purpose — education, scheme, or job?"},
    ],
  },
  {
    id: "birth_certificate",
    title: "Birth Certificate Application",
    category: "Municipal / CRS",
    fill_mode: "paper_or_online",
    official_form: "CRS Form No. 1 — Birth Report (RBD Act)",
    source_url: "https://crsorgi.gov.in/web/uploads/download/all_forms_CRS_2019_new.pdf",
    tagline: "CRS Form 1 still published; portal online in many states; CSC for home births.",
    why: "ORGI still publishes Form No.1 Birth Report. Central CRS portal covers many States/UTs online; crsorgi notes CSC login for domiciliary (home) births within 21 days. Child/parent name and DOB must align across hospital slip and Aadhaar.",
    required_docs: ["Aadhaar Card"],
    optional_docs: ["Hospital Discharge", "Ration Card", "School Certificate"],
    portal: {
      name: "CRS / State municipal birth registration",
      url: "https://crsorgi.gov.in",
    },
    form_fields: [
      {"key": "child_name", "label": "Child's Full Name", "high_stakes": true, "compare_to": "full_name", "prompt_hi": "बच्चे का पूरा नाम बताइए।", "prompt_en": "Child's full name."},
      {"key": "full_name", "label": "Parent / Informant Name", "high_stakes": true, "compare_to": "full_name", "compare_doc": "Aadhaar Card", "prompt_hi": "माता-पिता या सूचना देने वाले का नाम बताइए।", "prompt_en": "Parent or informant's name."},
      {"key": "father_name", "label": "Father's Name", "high_stakes": true, "compare_to": "father_name", "prompt_hi": "पिता का नाम बताइए।", "prompt_en": "Father's name."},
      {"key": "mother_name", "label": "Mother's Name", "high_stakes": true, "compare_to": null, "prompt_hi": "माता का नाम बताइए।", "prompt_en": "Mother's name."},
      {"key": "dob", "label": "Date of Birth of Child", "high_stakes": true, "compare_to": "dob", "prompt_hi": "बच्चे की जन्म तिथि बताइए।", "prompt_en": "Child's date of birth."},
      {"key": "place_of_birth", "label": "Place of Birth (hospital / home + city)", "high_stakes": true, "compare_to": null, "prompt_hi": "जन्म कहाँ हुआ — अस्पताल या घर, शहर?", "prompt_en": "Place of birth — hospital or home, city."},
      {"key": "aadhaar_number", "label": "Parent Aadhaar Number", "high_stakes": true, "compare_to": "id_number", "compare_doc": "Aadhaar Card", "prompt_hi": "माता-पिता का आधार नंबर बताइए।", "prompt_en": "Parent's Aadhaar number."},
      {"key": "mobile", "label": "Mobile Number", "high_stakes": true, "compare_to": null, "prompt_hi": "मोबाइल नंबर बताइए।", "prompt_en": "Mobile number."},
      {"key": "address", "label": "Parents' Address with PIN", "high_stakes": true, "compare_to": "address", "compare_doc": "Aadhaar Card", "prompt_hi": "माता-पिता का पता पिनकोड के साथ बताइए।", "prompt_en": "Parents' address with pincode."},
    ],
  },
  {
    id: "bank_aadhaar_seed",
    title: "Bank Aadhaar Seeding / KYC Update",
    category: "Banking",
    fill_mode: "assisted_counter",
    official_form: "Bank/BC Aadhaar consent + NPCI mapper seeding (not a national ICR form)",
    source_url: "https://uidai.gov.in/en/309-faqs/direct-benefit-transfer-dbt/about-dbt/12663-how-do-i-receive-benefits-under-the-govt-schemes-in-my-bank-account.html",
    tagline: "UIDAI: visit branch, fill bank mandate/consent — bank seeds NPCI mapper.",
    why: "UIDAI DBT FAQ: visit the bank branch and request linking by filling the bank's mandate and consent form; bank seeds the account on the NPCI mapper. Not a national ICR form — include because DBT fails when passbook name ≠ Aadhaar.",
    required_docs: ["Aadhaar Card", "Bank Passbook"],
    optional_docs: ["PAN Card", "Voter ID"],
    portal: {
      name: "Bank branch / BC — NPCI Aadhaar seeding",
      url: "https://www.npci.org.in",
    },
    form_fields: [
      {"key": "full_name", "label": "Name as on Bank Account", "high_stakes": true, "compare_to": "full_name", "compare_doc": "Bank Passbook", "prompt_hi": "बैंक खाते पर लिखा नाम बताइए।", "prompt_en": "Name as printed on the bank account."},
      {"key": "aadhaar_number", "label": "Aadhaar Number to Seed", "high_stakes": true, "compare_to": "id_number", "compare_doc": "Aadhaar Card", "prompt_hi": "जिस आधार को जोड़ना है वह नंबर बताइए।", "prompt_en": "Aadhaar number to seed."},
      {"key": "account_number", "label": "Bank Account Number", "high_stakes": true, "compare_to": "id_number", "compare_doc": "Bank Passbook", "prompt_hi": "बैंक खाता संख्या बताइए।", "prompt_en": "Bank account number."},
      {"key": "ifsc", "label": "IFSC Code", "high_stakes": true, "compare_to": null, "prompt_hi": "आईएफएससी कोड बताइए।", "prompt_en": "IFSC code."},
      {"key": "mobile", "label": "Mobile Linked to Account", "high_stakes": true, "compare_to": null, "prompt_hi": "खाते से जुड़ा मोबाइल बताइए।", "prompt_en": "Mobile linked to the account."},
      {"key": "dob", "label": "Date of Birth", "high_stakes": true, "compare_to": "dob", "compare_doc": "Aadhaar Card", "prompt_hi": "जन्म तिथि बताइए।", "prompt_en": "Date of birth."},
      {"key": "request_type", "label": "Seed / Re-seed / KYC Update", "high_stakes": true, "compare_to": null, "prompt_hi": "सीडिंग, दोबारा सीडिंग, या केवाईसी अपडेट?", "prompt_en": "Seed, re-seed, or KYC update?"},
    ],
  },
  {
    id: "gazette_name_change",
    title: "Gazette Name Change (Part IV)",
    category: "Gazette / Name",
    fill_mode: "paper_block_letters",
    official_form: "Change of Name (Adult/Major) — Gazette of India Part IV",
    source_url: "https://deptpub.gov.in/document-category/con-guidelines/",
    tagline: "Clearest still-manual identity stack — newspaper, deed, typed proforma, post/person submit.",
    why: "Department of Publication guidelines: documents submitted personally or by post to Civil Lines, Delhi — no agents/advocates channel. Needs newspaper notice, undertaking/deed, computer-typed proforma signed in OLD name with two witnesses, photos, Bharatkosh fee. Unlocks significant PAN/Aadhaar/passport name changes.",
    required_docs: ["Aadhaar Card"],
    optional_docs: ["PAN Card", "Passport", "Voter ID", "Newspaper Cutting"],
    portal: {
      name: "Department of Publication / eGazette",
      url: "https://egazette.gov.in",
    },
    form_fields: [
      {"key": "full_name", "label": "Present / Old Full Name (as signed on proforma)", "high_stakes": true, "compare_to": "full_name", "compare_doc": "Aadhaar Card", "prompt_hi": "पुराना पूरा नाम बताइए — जैसा अभी दस्तावेज़ों पर है।", "prompt_en": "Present/old full name as currently on documents."},
      {"key": "new_name", "label": "New Full Name Sought", "high_stakes": true, "compare_to": null, "prompt_hi": "नया पूरा नाम बताइए जो गजट में चाहिए।", "prompt_en": "New full name to appear in the gazette."},
      {"key": "father_name", "label": "Father's / Husband's Name", "high_stakes": true, "compare_to": "father_name", "compare_doc": "Aadhaar Card", "prompt_hi": "पिता या पति का नाम बताइए।", "prompt_en": "Father's or husband's name."},
      {"key": "dob", "label": "Date of Birth", "high_stakes": true, "compare_to": "dob", "compare_doc": "Aadhaar Card", "prompt_hi": "जन्म तिथि बताइए।", "prompt_en": "Date of birth."},
      {"key": "aadhaar_number", "label": "Aadhaar Number", "high_stakes": true, "compare_to": "id_number", "compare_doc": "Aadhaar Card", "prompt_hi": "आधार नंबर बताइए।", "prompt_en": "Aadhaar number."},
      {"key": "mobile", "label": "Mobile Number", "high_stakes": true, "compare_to": null, "prompt_hi": "मोबाइल नंबर बताइए।", "prompt_en": "Mobile number."},
      {"key": "address", "label": "Address with PIN", "high_stakes": true, "compare_to": "address", "compare_doc": "Aadhaar Card", "prompt_hi": "पूरा पता पिनकोड के साथ बताइए।", "prompt_en": "Full address with pincode."},
      {"key": "reason", "label": "Reason for Name Change", "high_stakes": true, "compare_to": null, "prompt_hi": "नाम बदलने का कारण बताइए।", "prompt_en": "Reason for changing the name."},
      {"key": "newspaper_details", "label": "Newspaper Notice (paper + date)", "high_stakes": true, "compare_to": null, "prompt_hi": "किस अखबार में नोटिस छपा और तारीख?", "prompt_en": "Which newspaper carried the notice, and on what date?"},
    ],
  },
  {
    id: "pan_new_49a",
    title: "New PAN — Form 49A",
    category: "Tax / PAN",
    fill_mode: "paper_or_online",
    official_form: "Form 49A — Application for Allotment of PAN (Individual)",
    source_url: "https://tin.tin.nsdl.com/pan/form49ACombine.html",
    tagline: "Online fill → print signed ack → physical POI/POA/DOB proofs (or CSC lane).",
    why: "Protean/UTIITSL Form 49A: do’s still say block letters in English; after online fill, signed acknowledgment plus physical proofs are commonly posted or handled via CSC. Name on application must match POI/POA/PODB exactly — same mismatch class as Aadhaar.",
    required_docs: ["Aadhaar Card"],
    optional_docs: ["Bank Passbook", "Voter ID", "Passport", "Ration Card"],
    portal: {
      name: "Protean / UTIITSL — Apply for New PAN",
      url: "https://www.onlineservices.nsdl.com/paam/endUserRegisterContact.html",
    },
    form_fields: [
      {"key": "full_name", "label": "Full Name (no titles; as on POI)", "high_stakes": true, "compare_to": "full_name", "compare_doc": "Aadhaar Card", "prompt_hi": "पूरा नाम बताइए जैसा पहचान पत्र पर है — उपाधि न लगाएँ।", "prompt_en": "Full name as on proof of identity, without titles."},
      {"key": "father_name", "label": "Father's Name", "high_stakes": true, "compare_to": "father_name", "compare_doc": "Aadhaar Card", "prompt_hi": "पिता का नाम बताइए।", "prompt_en": "Father's name."},
      {"key": "dob", "label": "Date of Birth", "high_stakes": true, "compare_to": "dob", "compare_doc": "Aadhaar Card", "prompt_hi": "जन्म तिथि बताइए।", "prompt_en": "Date of birth."},
      {"key": "aadhaar_number", "label": "Aadhaar Number", "high_stakes": true, "compare_to": "id_number", "compare_doc": "Aadhaar Card", "prompt_hi": "आधार नंबर बताइए।", "prompt_en": "Aadhaar number."},
      {"key": "mobile", "label": "Mobile Number", "high_stakes": true, "compare_to": null, "prompt_hi": "मोबाइल नंबर बताइए।", "prompt_en": "Mobile number."},
      {"key": "email", "label": "Email Address", "high_stakes": true, "compare_to": null, "prompt_hi": "ईमेल पता बताइए।", "prompt_en": "Email address."},
      {"key": "address", "label": "Address for Communication (with PIN)", "high_stakes": true, "compare_to": "address", "compare_doc": "Aadhaar Card", "prompt_hi": "पत्राचार का पता पिनकोड के साथ बताइए।", "prompt_en": "Communication address with pincode."},
      {"key": "name_on_card", "label": "Name to Print on PAN Card", "high_stakes": true, "compare_to": "full_name", "compare_doc": "Aadhaar Card", "prompt_hi": "पैन कार्ड पर कौन सा नाम छपे — पूरा या संक्षिप्त?", "prompt_en": "Name to print on the PAN card — full or abbreviated?"},
    ],
  },
];

export function getService(id: string) {
  const s = SERVICES.find((x) => x.id === id);
  if (!s) throw new Error(`Unknown service: ${id}`);
  return s;
}
